# -*- coding: utf-8 -*-
"""Financeanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuTBxFi15tIMHfCe2XcZRSnPoXZ55hBt
"""

import pandas as pd
url = "https://www.screener.in/company/TCS/consolidated/"
tables = pd.read_html(url)
len(tables)

print (tables[1].head())

income_statement = tables[1]
balance_sheet = tables[6]
cash_flow = tables[7]

def clean_df(df):
    df = df.replace(',', '', regex=True)
    df = df.replace('-', None)
    return df

income_statement = clean_df(income_statement)
balance_sheet = clean_df(balance_sheet)
cash_flow = clean_df(cash_flow)

print(income_statement.info())

print(income_statement.isnull().sum())

income_statement = income_statement.drop(columns=["TTM"], errors="ignore")

print(income_statement.isnull().sum())

print(balance_sheet.isnull().sum())
print(cash_flow.isnull().sum())

print(balance_sheet.info())

for col in income_statement.columns[1:]:
    income_statement[col] = pd.to_numeric(income_statement[col], errors='coerce')

for col in balance_sheet.columns[1:]:
    balance_sheet[col] = pd.to_numeric(balance_sheet[col], errors='coerce')

for col in cash_flow.columns[1:]:
    cash_flow[col] = pd.to_numeric(cash_flow[col], errors='coerce')

print(income_statement.columns.tolist())

income_statement.rename(
    columns={income_statement.columns[0]: 'Account'},
    inplace=True)

print(income_statement.columns.tolist())

balance_sheet.rename(
    columns={balance_sheet.columns[0]: 'Account'},
    inplace=True)

cash_flow.rename(
    columns={cash_flow.columns[0]: 'Account'},
    inplace=True)

income_statement = income_statement[['Account','Mar 2020','Mar 2021','Mar 2022','Mar 2023','Mar 2024']]
balance_sheet = balance_sheet[['Account','Mar 2020','Mar 2021','Mar 2022','Mar 2023','Mar 2024']]
cash_flow = cash_flow[['Account','Mar 2020','Mar 2021','Mar 2022','Mar 2023','Mar 2024']]

income_statement.columns = ['Account','FY20','FY21','FY22','FY23','FY24']
balance_sheet.columns = ['Account','FY20','FY21','FY22','FY23','FY24']
cash_flow.columns = ['Account','FY20','FY21','FY22','FY23','FY24']

print(income_statement.columns.tolist())
print(balance_sheet.columns.tolist())
print(cash_flow.columns.tolist())

income_t = income_statement.set_index('Account').T.reset_index()
income_t.rename(columns={'index':'Year'}, inplace=True)

balance_t = balance_sheet.set_index('Account').T.reset_index()
balance_t.rename(columns={'index':'Year'}, inplace=True)

cashflow_t = cash_flow.set_index('Account').T.reset_index()
cashflow_t.rename(columns={'index':'Year'}, inplace=True)

print(income_t.columns)

income_t.columns = income_t.columns.str.replace('[+,%]', '', regex=True).str.strip().str.replace(' ', '_').str.lower()
balance_t.columns = balance_t.columns.str.replace('[+,%]', '', regex=True).str.strip().str.replace(' ', '_').str.lower()
cashflow_t.columns = cashflow_t.columns.str.replace('[+,%]', '', regex=True).str.strip().str.replace(' ', '_').str.lower()

print(income_t.columns)

income_t['revenue_growth_%'] = income_t['sales'].pct_change()*100
income_t['net_profit_margin_%'] = (income_t['net_profit'] / income_t['sales'])*100

income_t['company'] = 'Tata_Motors'
balance_t['company'] = 'Tata_Motors'
cashflow_t['company'] = 'Tata_Motors'

income_t.to_csv("tata_motors_income_transposed.csv", index=False)
balance_t.to_csv("tata_motors_balance_transposed.csv", index=False)
cashflow_t.to_csv("tata_motors_cashflow_transposed.csv", index=False)

import sqlite3
import pandas as pd

income_t.to_csv("tata_motors_income_statemen.csv", index=False)
balance_t.to_csv("tata_motors_balance_sheet.csv", index=False)
cashflow_t.to_csv("tata_motors_cash_flow.csv", index=False)

from google.colab import files
files.download("tata_motors_income_statemen.csv")
files.download("tata_motors_balance_sheet.csv")
files.download("tata_motors_cash_flow.csv")