# -*- coding: utf-8 -*-
"""zara_sales_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIlXpSCyvnuZTOdo-ahQbvO9FmnpzVZ6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("ZARA sales COPY export 2025-12-02 09-05-07.csv")
print(df)

print(df.info())

print(df.isnull().sum())

print(df.columns.tolist())

cols_to_drop = [
    "description", "url", "scraped_at"]
df = df.drop(columns=cols_to_drop, errors="ignore")

df.columns = df.columns.str.lower().str.replace(' ', '_')
print(df.columns.tolist())

print(df[df['name'].isna()])

df['name'] = df['name'].fillna('unknown')

print(df.isnull().sum())

cols = ["promotion","seasonal"]

df[cols] = df[cols].replace({'Yes': 1, 'No': 0}).astype(int)

print(df["promotion"])

import sqlite3

# Create/connect a database file
conn = sqlite3.connect('my_database.db')

df.to_sql("zara_analysis", conn, if_exists='replace', index=False)

query = "SELECT * FROM zara_analysis LIMIT 5;"
print(pd.read_sql(query, conn))
conn.close()

import sqlite3
import pandas as pd

df.to_csv("zara_analysis.csv", index=False)

from google.colab import files
files.download("zara_analysis.csv")